AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  Include:
    - '**/*.rb'
    - 'Gemfile'
    - 'Rakefile'
  Exclude:
    - 'logs/**/*'
    - '.git/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 40

Metrics/MethodLength:
  Max: 25

Metrics/ParameterLists:
  Max: 7
