AllCops:
  TargetRubyVersion: 3.3.8
  NewCops: enable
  Include:
    - '**/*.rb'
    - 'Gemfile'
    - 'Rakefile'
  Exclude:
    - 'logs/**/*'
    - '.git/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 40
  Exclude:
    - './lib/mixins/rpc_handlers.rb'
    - './lib/mixins/election_management.rb'

Metrics/MethodLength:
  Max: 40

Metrics/ParameterLists:
  Max: 7

Metrics/BlockLength:
  Max: 40

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/PerceivedComplexity:
  Max: 10
