AllCops:
  TargetRubyVersion: 3.3.8
  NewCops: enable
  Include:
    - '**/*.rb'
    - 'Gemfile'
    - 'Rakefile'
  Exclude:
    - 'logs/**/*'
    - '.git/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 60

Metrics/MethodLength:
  Max: 40

Metrics/ParameterLists:
  Max: 7

Metrics/BlockLength:
  Max: 40

Metrics/CyclomaticComplexity:
  Max: 14

Metrics/PerceivedComplexity:
  Max: 15

Metrics/ModuleLength:
  Max: 170
